### ISSUE TITLE
Closing files - leak

### ISSUE THREAD

**Issue by doronAtuar** [image-size/image-size#202]
When I run this code 
```javascript
const sizeOf = require('image-size');

var i = 0
while (true) {
    sizeOf('image.jpg', function (err, dimensions) {
        //   console.log(dimensions.width, dimensions.height);
    });
    if ((i++ % 100) == 0) {
        console.log(`usage: ${process.memoryUsage().heapUsed / 1024 / 1024} `);
    }
}
```
It prints
```bash
usage: 3.9852752685546875
usage: 4.6635894775390625
usage: 4.832130432128906
usage: 4.996772766113281
usage: 5.164299011230469
usage: 5.328941345214844
usage: 5.500404357910156
usage: 5.664344787597656
usage: 5.828071594238281
usage: 5.005210876464844
usage: 5.168937683105469
usage: 5.3328094482421875
usage: 5.49658203125
usage: 5.660438537597656
usage: 6.074180603027344


...

usage: 279.1095428466797
usage: 279.2576370239258
usage: 279.4058532714844
usage: 279.5539245605469
usage: 279.70214080810547
usage: 279.85028076171875
usage: 279.99849700927734
usage: 280.14656829833984
usage: 280.2948226928711
usage: 280.4428939819336
usage: 280.5911102294922
usage: 280.73924255371094
usage: 280.88745880126953
usage: 281.03553009033203
usage: 281.1837463378906
usage: 281.3319778442383
usage: 281.4801940917969
usage: 281.6282653808594
internal/process/per_thread.js:136
    _memoryUsage(memValues);

Error: ENFILE: file table overflow, uv_resident_set_memory
    at process.memoryUsage (internal/process/per_thread.js:136:5)
    at Object.<anonymous> (/var/www/cropper/dbTools/training/bb/bug.js:9:39)
    at Module._compile (internal/modules/cjs/loader.js:778:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:789:10)
    at Module.load (internal/modules/cjs/loader.js:653:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:593:12)
    at Function.Module._load (internal/modules/cjs/loader.js:585:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:831:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

How do I close the file?

This problem doesn't happen when using the Synchronous method

```javascript
const sizeOf = require('image-size');

var i = 0
while (true) {
    var dim = sizeOf('image.jpg')
    if ((i++ % 100) == 0) {
        console.log(`usage: ${process.memoryUsage().heapUsed / 1024 / 1024} `);
    }
}
```

```bash
usage: 6.689292907714844
usage: 6.955757141113281
usage: 7.222099304199219
usage: 7.488594055175781
usage: 7.754913330078125
usage: 8.021430969238281
usage: 8.287750244140625
usage: 6.610832214355469
usage: 6.8771514892578125
usage: 7.14361572265625
usage: 7.4099273681640625
usage: 7.676475524902344
usage: 7.9427947998046875
usage: 8.209274291992188
usage: 8.475593566894531
usage: 6.797630310058594
usage: 7.064064025878906
usage: 7.330528259277344
```

Version: 0.7.4
node: v10.16.3
Ubuntu: 18

**Comment by netroy** [comment]
thanks for the issue. I'll look into it.

**Comment by netroy** [comment]
@doronAtuar this is happening because in async mode, your code executes for all in parallel. this causes a really large number of open file descriptor.

I'm assuming you have a really high ulimit value set. otherwise you'd have got `EMFILE: too many open files` instead.
This does not happen in sync mode because that code only has one file descriptor open at any time.

I suppose adding a queue for the async function would fix this issue.
if there is an urgent need in production, let me know. I can prioritize this.

**Comment by doronAtuar** [comment]
Hey, Thanks for the quick response
That is true, 
```bash
$ ulimit -n
500000
```
I am iterating over 2000000 images when this happens

Using the sync method degraded the execution drastically

**Comment by doronAtuar** [comment]
>  if there is an urgent need in production, let me know. I can prioritize this.
Yes, That would be very helpful

**Comment by netroy** [comment]
@doronAtuar I've added a queue with a default concurrency of 100. You can read more in the Readme.
Now your test code doesn't crash anymore.
However there still seems to be some string concatenation leaks in the nodejs itself.
A few of them got fixed between node 8 & node 12. but, there is still a leak of about 73MB for every 100k operations.

I'm gonna leave this at it is for now, & keep this ticket open until I figure out as fix.

The fix for you has been released in `v0.8.0`

**Comment by doronAtuar** [comment]
Thank you very much for taking the time to solve this!
I will have a look in the next few days.

**Comment by netroy** [comment]
This doesn't seem to happen anymore on the latest release on node 12+.
Marking this as done.
