### ISSUE TITLE
Is there a way to get the size of an array of images all at once?

### ISSUE THREAD

**Issue by Shvan11** [image-size/image-size#376]

**Comment by netroy** [comment]
Generally when opening an issue on any repo, please include as much information as possible, so that the people answering have to make the least amount of assumptions.

For now, I'm assuming that you have an array of file-paths, so you could do something like this:

```typescript
const filePaths = ['/tmp/file1', '/tmp/file2'] // This is your array

const { promisify } = require('util')
const sizeOf = promisify(require('image-size'))

const sizes = await Promise.all(filePaths.map(filePath => sizeOf(filePath))
```

When this is done `sizes` will be an array of [`ISize`](https://github.com/image-size/image-size/blob/main/lib/types/interface.ts#L1)
