### ISSUE TITLE
Doesn't work if you use it inside an async function

### ISSUE THREAD

**Issue by s1nistr4** [image-size/image-size#390]
```
const sizeOf = require('image-size')
async function MyFunc():Promise<void> {
  const dimensions = sizeOf('images/funny-cats.png')
  return dimensions
}

const dimensions = await MyFunc()
console.log(dimensions.width) 
```

This does not work and leaves the program stuck forever without the function returning anything.

**Comment by netroy** [comment]
The library was written way before nodejs had native support for promises or async-await.
That's why [you need to use `utils.promisify` as documented in the readme](https://github.com/image-size/image-size#using-promises-nodejs-10x).

Another way would be to do it like this
```typescript
const sizeOf = require('image-size')
async function MyFunc(): Promise<void> {
  return new Promise(resolve => sizeOf('images/funny-cats.png', resolve))
}

const dimensions = await MyFunc()
console.log(dimensions.width) 
```

The version 2 of this library will have native promises support, but that's not out yet.
