### ISSUE TITLE
/node_modules/image-size/dist/index.js:36; size.type = size.type ?? type; Unexpected token ?

### ISSUE THREAD

**Issue by avinashdowntempo** [image-size/image-size#398]
getting the below error

/node_modules/image-size/dist/index.js:36
; size.type = size.type ?? type;
Unexpected token ?

**Comment by netroy** [comment]
What version of node.js are you on?

**Comment by netroy** [comment]
`??` is [Nullish coalescing operator](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Operators/Nullish_coalescing), which is supported in node.js since 14.0.
This error means that you are using a version older than 14.0, which hasn't been supported by this library for a few years now.
