### ISSUE TITLE
Height and width of JPEG are swapped

### ISSUE THREAD

**Issue by SirVizzy** [image-size/image-size#407]
I have a JPEG image with dimensions of 3000 x 4000 which I am trying to detect using this package. However, instead of getting `{ width: 3000, height: 4000 }` I am getting `{ width: 4000, height: 3000 }`.

Why is this?

I have converted the image to PNG as well and then it works correctly. Feels a bit unreliable?

**Comment by netroy** [comment]
Can you check the JPEG EXIF data to see if the image is rotated in the metadata? This is quite common. [Relevant section in the Readme](https://github.com/image-size/image-size/blob/main/Readme.md?plain=1#L150).

**Comment by SirVizzy** [comment]
Orientation of the image is "Rotate 90 CW" or "6" - does this mean the camera set the invalid orientation for the image?

**Comment by netroy** [comment]
This library is just reading what's in the EXIF data in the image. Only you as a user of the image can decide if this data is valid or not.

**Comment by SirVizzy** [comment]
> This library is just reading what's in the EXIF data in the image. Only you as a user of the image can decide if this data is valid or not.

Thanks. I was under the assumption this library would render the image and take values from there.

**Comment by SirVizzy** [comment]
> Would it be helpful if this library accepted an additional flag to auto-rotate the dimensions based on the EXIF orientation data?

Seems like a good feature to have!

**Comment by BrodaNoel** [comment]
I can't believe this...
Imagine creating a library to get the size of an image, and returning it swapped "because the exif"...

**Comment by BrodaNoel** [comment]
Whoever created this library, I just want to let you know that I have to re-process more than 120 TB in photos, just cause the `image-size` library does not return `the-image-size`, but `the-image-exif-size`.

It's unbelievable how much I hate the development world today.

I hate my whole life.

<img width="460" alt="Screen Shot 2024-11-07 at 01 46 33" src="https://github.com/user-attachments/assets/80eb8b39-8c36-4e3c-90b3-c50e5128caab">

I'm LITERALLY right now opening SkyScanner. I need 2 weeks off. Thanks, whoever you are.

**Comment by netroy** [comment]
> I can't believe this...
> Imagine creating a library to get the size of an image, and returning it swapped "because the exif"...

if you use any low-level image metadata tool, they will not automatically swap width and height based on the orientation defined in exif. **that is the responsibility of the user**. 

> I have to re-process more than 120 TB in photos

I'm not sure how I'm at fault here. Should you not have tested this on a smaller set of images first, and should you not have saved the orientation data along with the width/height, that could then be used to perform any corrections without reprocessing the images.


> It's unbelievable how much I hate the development world today.
> 
> I hate my whole life.

to me it sounds like I should have never created this library, and should have definitely not made it freely available.

I'm sorry for making you suffer because of my free labour.
