### ISSUE TITLE
Help Needed: Add support for JPEG XL

### ISSUE THREAD

**Issue by cascading-jox** [image-size/image-size#408]
Are there any plans to support [JPEG XL](https://jpeg.org/jpegxl/)? More and more companies and organisations have [voiced their support and started to adopt it](https://en.wikipedia.org/wiki/JPEG_XL#Industry_support_and_adoption).

**Comment by netroy** [comment]
I tried a few months ago, but had to give up because I could not any details on where in the `jxlp`/`jxlc` box to read the basic metadata from. I tried reading all 16 bit and 32 bit numbers (tried both endianness), but did not find the data I needed. Perhaps I'm just looking in the wrong box, so I tried looking into how libjxl read this data, and I could not manage to understand their code.

**Comment by netroy** [comment]
rebase the branch [here](https://github.com/image-size/image-size/pull/409).
I still can't find and docs for where to find the metadata in a jpeg-xl file.
If someone could find that info, we can try to update the PR.

**Comment by netroy** [comment]
Addressed in #409, and released in `v1.2.0`.
