### ISSUE TITLE
TypeError: invalid jpg

### ISSUE THREAD

**Issue by andreyvolokitin** [image-size/image-size#5]
I have a bunch of .jpg images which I saved from Photoshop CS6. But for all of them I get this error, so I can’t process them. When I tried to process sample image from repository - it worked.

**Comment by jhyjhy** [comment]
May I know in which version the author fixed it?

and  the 2.0.0beta version is relatively stable ?
@netroy

**Comment by netroy** [comment]
This particular bug is 7 years old, and was fixed in one of the releases around that time.
![image](https://github.com/image-size/image-size/assets/196144/eac40716-da7f-4ae5-afa2-f97435918027)

If you are seeing a `TypeError: invalid jpg` error, then please create a new ticket for it.

Regarding 2.0 beta, unless you need ESM support, you should continue using 1.x releases for now, as 2.0 has no new features.
